language: ruby
rvm:
  - "2.1.0"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/stripe.travis.yml config/stripe.yml
  - psql -c 'create database prague_test' -U postgres